export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const PORTAL_ROUTE = '/portal'
export const BRAIN_ROUTE = '/brain'
export const SIB_ROUTE = '/'
export const PROFILE_ROUTE = '/profile'
export const ALL_BRAINS_ROUTE = '/allbrains'